import os
import napari
import random
from voldist_tools.basictools import wipe_layers, view_saved_files

'''
Opens a napari viewer. The key press "n" will open cell cube (generated by cell_cubes_create).
'''

if __name__ == '__main__':

    main_dir = '/Volumes/bigData/wholeMount_volDist/220712_Fix_Emb_Flvw_Chn1GAP_PI_aTub647_Processed/N2V_Denoised/0_Analysis_01/0_data_cubes/processed_cubes'
    cube_paths = [os.path.join(main_dir, s) for s in os.listdir(main_dir) if not s.startswith('.') and not 'results' in s] 
    subdirs = [s for s in os.listdir(main_dir) if not s.startswith('.') and not 'results' in s]

    #random.shuffle(cube_paths)

    viewer = napari.Viewer(title = 'this is the cube viewer')

    @viewer.bind_key('n')
    def next_cube(viewer):
        wipe_layers(viewer)
        # define next_path variable as global
        next_path = cube_paths.pop(0)
        view_saved_files(next_path, viewer)
        cube_name = "_".join(next_path.rsplit('/', 2)[1:])
        print(f'Now viewing {cube_name}')

    napari.run()








            